
    </div><!--container-->
</div><!--wrap-->

<footer class="navbar-inverse navbar-fixed-bottom navbar footer">
    <div class="container">
        <div class="pull-left">
            <span class="itemHide">&copy; AuroraFT 2017</span>
        </div>

        <div class="pull-right">
            <a href="<?php echo $www?>privacy">Privacy</a><span> . </span>
            <a href="<?php echo $www?>terms">Termini di utilizzo</a>
        </div>
    </div><!--container-->
</footer>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script src="https://unpkg.com/simplebar@latest/dist/simplebar.js"></script>

</body>
</html>
