<?php echo $this->fetch("header.phtml", $data); ?>
    <div>
        <div class="row home-top">
            <div class="col-md-6 col-md-offset-3">
                <div class="jumbotron">
                    <h1>Zeygos Radar</h1>
                    <!--<p class="lead">This is such a great app!</p>-->

                    <?php if(isset($user) && !empty($user)) { ?>

                    <?php } else { ?>
                        <div class="centered">
                            <p>
				<a class="btn btn-lg btn-success" href="<?php echo $www?>login">Login</a> o
                                <a class="btn btn-lg btn-success" href="<?php echo $www?>register">Registrati</a>
                            </p>

                        </div>
                    <?php } ?>

                </div>
            </div>
        </div>
    </div>

<script type="text/javascript">activateParticles();</script>
<?php echo $this->fetch("footer.phtml", $data); ?>
