<?php echo $this->fetch("header.phtml", $data); ?>

<div class="row">
    <div class="col-xs-8 col-xs-offset-2 col-md-4 col-md-offset-4">
        <h2>Reset Password</h2>
        <p>Please choose your new password:</p>
    </div>
</div><!--row-->

<div class="row">
    <div class="col-xs-8 col-xs-offset-2 col-md-4 col-md-offset-4">

        <form id="password-form" action="<?php echo $www?>password-reset?token=<?php echo $token; ?>" accept-charset="UTF-8" method="POST" role="form">
            <div class="form-group">
                <label class="control-label" for="password">New Password*</label>
                <input type="password" id="password" class="form-control"
                       name="password" placeholder="********" tabindex="5" value="<?=isset($input['password']) ? $input['password'] : '';?>">
                <?php if (isset($errors['password'][0])) { ?>
                    <label id="password_error" class="error" for="password">
                        <?php echo $errors['password'][0]; ?>
                    </label>
                <?php } ?>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-lg btn-success btn-block" tabindex="4" name="reset-button">Save</button>
            </div>
        </form>
    </div>
</div><!--row-->

<script src="<?php echo $www?>public/js/jquery.validate.min.js"></script>
<script type="text/javascript">
    $().ready(function () {

        // Form validation on keyup and submit
        $("#password-form").validate({
            rules: {
                password: {
                    required: true,
                    minlength: 6
                }
            },
            messages: {
                password: {
                    required: "Please provide a password.",
                    minlength: "Your password must be at least 6 characters long."
                }
            }
        });
    });
</script>

<?php echo $this->fetch("footer.phtml", $data); ?>