<?php echo $this->fetch("header.phtml", $data); ?>

<div class="row">
    <div class="col-xs-8 col-xs-offset-2 col-md-4 col-md-offset-4">
        <h2>Reset Password Request</h2>
        <p>Please provide your email and we'll send a link to set up a new password.</p>
    </div>
</div><!--row-->

<div class="row">
    <div class="col-xs-8 col-xs-offset-2 col-md-4 col-md-offset-4">

        <form id="password-form" action="<?php echo $www?>password-reset-request" accept-charset="UTF-8" method="POST" role="form">
            <div class="form-group">
                <label class="control-label" for="email">Email*</label>
                <input type="email" id="email" class="form-control" name="email"
                       maxlength="255" placeholder="john@example.com" tabindex="2" value="<?=isset($input['email']) ? $input['email'] : '';?>">
                <?php if (isset($errors['email'][0])) { ?>
                    <label id="email_error" class="error" for="email">
                        <?php echo $errors['email'][0]; ?>
                    </label>
                <?php } ?>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-lg btn-success btn-block" tabindex="4" name="reset-button">Send</button>

            </div>
        </form>
    </div>
</div><!--row-->

<script src="<?php echo $www?>public/js/jquery.validate.min.js"></script>
<script type="text/javascript">
    $().ready(function () {

        // Form validation on keyup and submit
        $("#password-form").validate({
            rules: {
                email: {
                    required: true,
                    email: true
                }
            },
            messages: {
                email: "Please enter a valid email address."
            }
        });
    });
</script>

<?php echo $this->fetch("footer.phtml", $data); ?>