<?php echo $this->fetch("header.phtml", $data); ?>

    <ul class="breadcrumb">
        <li><a href="<?php echo $www?>">Home</a></li>
        <li class="active">Change Password</li>
    </ul>

    <div>
        <h1>Change Password</h1>
        <p>Please choose your new password:</p>

        <div class="col-xs-4 padding-left-none">
            <form id="password-form" action="<?php echo $www?>change-password" accept-charset="UTF-8" method="POST" role="form">
                <div class="form-group">
                    <label class="control-label" for="password">New Password*</label>
                    <input type="password" id="password" class="form-control"
                           name="password" placeholder="********" tabindex="5" value="<?=isset($input['password']) ? $input['password'] : '';?>">
                    <?php if (isset($errors['password'][0])) { ?>
                        <label id="password_error" class="error" for="password">
                            <?php echo $errors['password'][0]; ?>
                        </label>
                    <?php } ?>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-lg btn-success btn-block" tabindex="4" name="reset-button">Save</button>
                </div>
            </form>
        </div>
    </div>

<script src="<?php echo $www?>public/js/jquery.validate.min.js"></script>
<script type="text/javascript">
    $().ready(function () {

        // Form validation on keyup and submit
        $("#password-form").validate({
            rules: {
                password: {
                    required: true,
                    minlength: 6
                }
            },
            messages: {
                password: {
                    required: "Please provide a password.",
                    minlength: "Your password must be at least 6 characters long."
                }
            }
        });
    });
</script>

<?php echo $this->fetch("footer.phtml", $data); ?>