<?php echo $this->fetch("header.phtml", $data); ?>

    <ul class="breadcrumb">
        <li><a href="<?php echo $www?>">Home  </a></li>
        <li class="active">Terms</li>
    </ul>

    <div style="padding:50px;font-size:16px">

        <h2>Termini di utilizzo</h2>

<p>Il tool operativo &ldquo;Market Radar&rdquo; viene concesso in licenza d'uso ai clienti di Zeygos. Esso si configura come una prestazione accessoria all'attivit&agrave; di trading. 
Il servizio esula quindi da qualsiasi prestazione di raccomandazione personalizzata in materia di Investimenti.</p>
 
<p>Il tool Market Radar &egrave; offerto in prova gratuita per i primi trenta giorni successivi all'iscrizione. Salvo cancellazione, la sottoscrizione si rinnover&agrave; in automatico ogni 30 giorni al costo (mensile) di 20 euro, che verr&agrave; addebitato direttamente sulla carta o sul conto Paypal forniti al momento dell'iscrizione. (es. attivazione 15 giugno, primo addebito 15 Luglio; &egrave; sufficiente disabilitarsi prima di tale termine per non avere alcun costo).</p>
 
 
<p>Le precedenti condizioni potranno essere variate tramite comunicazione per via telematica e il servizio &ldquo;Market Radar&ldquo; potr&agrave; essere in qualsiasi momento modificato o soppresso.</p>

<p>Zeygos non garantisce il perfetto funzionamento del programma, o l'esattezza e tempestivit&agrave; dei dati con esso forniti.</p>
 
<p>Il cliente attivando la fornitura del servizio d&agrave; esplicitamente il proprio consenso all'addebito sulla propria carta o conto Paypal dei relativi importi e prende altres&igrave; atto che Zeygos non risponde dell'autenticit&agrave;, tempestivita&rsquo;, veridicit&agrave; o affidabilit&agrave; dei dati di mercato, forniti da terzi, manlevandola pertanto da ogni responsabilit&agrave; in proposito, compresa quella relativa a perdite legate all&rsquo;attivita&rsquo; di trading/investimento basata sull&rsquo;utilizzo del tool &ldquo;Market Radar&rdquo;.</p>



<!--
<p>Il tool operativo “Market Radar” viene concesso in licenza d'uso ai clienti di Zeygos. Esso si configura come una prestazione accessoria all'attività di trading. 
Il servizio esula quindi da qualsiasi prestazione di raccomandazione personalizzata in materia di Investimenti.</p>
 
<p>Il tool Market Radar è offerto in prova gratuita per i primi trenta giorni successivi all'iscrizione. Salvo cancellazione, la sottoscrizione si rinnoverà in automatico ogni 30 giorni al costo (mensile) di 20 euro, che verrà addebitato direttamente sulla carta o sul conto Paypal forniti al momento dell'iscrizione. (es. attivazione 15 giugno, primo addebito 15 Luglio; è sufficiente disabilitarsi prima di tale termine per non avere alcun costo).</p>
 
 
<p>Le precedenti condizioni potranno essere variate tramite comunicazione per via telematica e il servizio Market Radar potrà essere in qualsiasi momento modificato o soppresso.</p>

<p>Zeygos non garantisce il perfetto funzionamento del programma, o l'esattezza e tempestività dei dati con esso forniti.</p>
 
<p>Il cliente attivando la fornitura del servizio dà esplicitamente il proprio consenso all'addebito sulla propria carta o conto Paypal dei relativi importi e prende altresì atto che Zeygos non risponde dell'autenticità, tempestivita’, veridicità o affidabilità dei dati di mercato, forniti da terzi, manlevandola pertanto da ogni responsabilità in proposito, compresa quella relativa a perdite legate all’attivita’ di trading/investimento basata sull’utilizzo del tool “Market Radar”.</p>

        <h1>Terms and Conditions ("Terms")</h1>
        <p>Please read these Terms and Conditions ("Terms", "Terms and Conditions") carefully before using the www.example.com website (the "Service") operated by My Awesome App ("us", "we", or "our").</p>

        <p>Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users and others who access or use the Service.</p>

        <p>By accessing or using the Service you agree to be bound by these Terms. If you disagree with any part of the terms then you may not access the Service. </p>


        <h2>Accounts</h2>

        <p>When you create an account with us, you must provide us information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service.</p>

        <p>You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password, whether your password is with our Service or a third-party service.</p>

        <p>You agree not to disclose your password to any third party. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.</p>


        <h2>Links To Other Web Sites</h2>

        <p>Our Service may contain links to third-party web sites or services that are not owned or controlled by My Awesome App.</p>

        <p>My Awesome App has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party web sites or services. You further acknowledge and agree that My Awesome App shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such web sites or services.</p>

        <p>We strongly advise you to read the terms and conditions and privacy policies of any third-party web sites or services that you visit.</p>


        <h2>Termination</h2>

        <p>We may terminate or suspend access to our Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p>

        <p>All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.</p>

        <p>We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p>

        <p>Upon termination, your right to use the Service will immediately cease. If you wish to terminate your account, you may simply discontinue using the Service.</p>

        <p>All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.</p>


        <h2>Governing Law</h2>

        <p>These Terms shall be governed and construed in accordance with the laws of Italy, without regard to its conflict of law provisions.</p>

        <p>Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. These Terms constitute the entire agreement between us regarding our Service, and supersede and replace any prior agreements we might have between us regarding the Service.</p>


        <h2>Changes</h2>

        <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will try to provide at least 30 days notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.</p>

        <p>By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, please stop using the Service.</p>


        <h2>Contact Us</h2>

        <p>If you have any questions about these Terms, please contact us.</p>

-->
   </div>

<?php echo $this->fetch("footer.phtml", $data); ?>